language: python
python:
- '3.6'
install:
- pip install coveralls
script:
- coverage run --source dkey setup.py nosetests
- coverage report -m
after_success:
- coveralls
deploy:
  skip_cleanup: true
  provider: pypi
  on:
    tags: true
  user:
    secure: ZYN/wuXcpWOuWtuEJrrdd7uhdID5yOk6XN9zeGgFVQASnI5PvgqGe/DeflMkSAem5gaa/shGNVL0454tI2L047HxN11MiGyk6wlDUAHbx6iQm4REzgHufxfmoVtqUXHnJqxARboTWw3vosorAd+u6fyhdcqI66bs4OEH23op2uCPSz05s5jgPDNkgFOjAetVfnnFEquEskVBoi0mor9BPGrswDdmFcgO/75qFYRru+BCp2+dxZvplgsFOVuLBigcp3Qw/INxbzNS694c1dDp3UApAWdr2GkWMnQrzfg3g/yydug7xHuRm3bCQp7rFFwhGlDKHGOq7YcQR4KBWr1efUq7BL+AEZFTqNvqDj1nTytGfUIDiluWogHZgh+TecjH1koVw+2k5Zz1aWESbxNoEfQMGj640GMxB1jFbeI/SNaBt7gs5Zx88wtVPUCUKab5Th+sXQvMUihP3gvCRLWSXnzjgwv5Fo6Ro8Vo4xeM7lhqqEkKyiL4E5TquQ626ayN5m3dZvEAxwHAOi2Uaky/LGAb9SJKUA5rwICYBU1YYGY7TA5qBbxDwpp/k2nqs2IyV11oMvlsfK3xs5E9cUn3MivZUAX9MQgvdlvij1G6lsc3a0RiHln1LYHnls6WembE1B8NO1RM4KitlIDWHGxFfPOYQpvqkotuABnF+gJL+es=
  password:
    secure: OKEQrOFbxC0kgPt0RkPUr0Oz+XCjDnSiMrHMJzT2Nm8J2XO1UDxpwWIeaq7gTFmLoNhImAroL/YsoNrHBkaQemEkxKC55Qnt5SBoZvdlspA7ozaBtVOZ7+hAs4k0yoNXxARt/7KxuN+5qhZxySfNBpaFClvMnzW7V/e+9kc759cFGkzimbiOwN+t/apTXKaO7IvdnYCpASeL1/W7yjlN56ea9LYC/AtIVqqiQrC8j2wbI78mxoJN2hiysSOfxwo/j5vMToSrHwHdLXGpqq0igU+bwdJi/0bNfw2wIrRQfFFbaYuryJgH6ilDKHwsKpbMFTfO2zHbhWYOVCWdrHf7n5DCj1cuGT6SQSxDVy5riGWSif6lPUD5eAlZsB2Y7mxwB650ptFJqSoRmwJXk+AXfrKalntNgirVid31NRLA1MSLcLa6QWVTqsD16vV+ScvYMwqr6Qvj41OUzD892kvD93tFCy85XRQAIpJX73KV9YdDJPbUHZz0XtmXebrguRe28y13PFHqPjJq4cT7OyjYSq6ObwyWCLatlf6IKNMWRq4bVfwr83uaWZjlqsahMMAx9LbZCiRGp8smYV65oBd5I3I33U4Udlm7we91MZp8JN0rxzrh7Y03w+kJwYIdIrTenB3Vx1tS1Vy+E48jeljfzRN9jEmCQ93LE5JmnfAHe68=
  distributions: "sdist bdist_wheel"
